/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_chevauchee_fantastique;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author mathi
 */
public class Interface_graphique_chevauchee_fantastique extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface_graphique_chevauchee_fantastique.class.getName());

    /**
     * Creates new form Interface_graphique_chevauchee_fantastique
     */
    private final Jeu jeu;
    private final JButton[][] grilleBoutons;
    private final javax.swing.JLabel labelEtat;

    public Interface_graphique_chevauchee_fantastique() {
        initComponents();
        this.jeu = new Jeu();
        this.grilleBoutons = new javax.swing.JButton[5][5];

        this.setTitle("La Chevauchée Fantastique");
        this.setSize(600, 650);

        // On définit la disposition globale (Etape 7 enrichie)
        this.getContentPane().setLayout(new java.awt.BorderLayout());

        // --- ÉTAPE 12 : CRÉATION DU LABEL D'ÉTAT ---
        labelEtat = new javax.swing.JLabel("Bonne chance !", javax.swing.SwingConstants.CENTER);
        labelEtat.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        this.getContentPane().add(labelEtat, java.awt.BorderLayout.SOUTH); // Placé en bas

        // Création du panneau pour la grille (Etape 7)
        javax.swing.JPanel panneauGrille = new javax.swing.JPanel(new java.awt.GridLayout(5, 5));
        this.getContentPane().add(panneauGrille, java.awt.BorderLayout.CENTER); // Au centre

        initialiserPlateau(panneauGrille);
    }

   private void initialiserPlateau(JPanel panneauGrille) { 
            for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            JButton btn = new JButton();
            this.grilleBoutons[i][j] = btn;

            final int x = i;
            final int y = j;

            btn.addActionListener(e -> {
                this.jeu.tenterUnCoup(x, y);
                actualiserAffichage();
            });

            // On ajoute le bouton au PANNEAU passé en paramètre
            panneauGrille.add(btn); 
        }
    }
    actualiserAffichage();
}

    /**
     * ÉTAPE 11 : Feedback Visuel Cette méthode redessine le plateau sans
     * recréer les boutons.
     */
    public void actualiserAffichage() {
        Damier damier = this.jeu.getDamier();
        Cavalier cavalier = this.jeu.getCavalier();

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                JButton btn = this.grilleBoutons[i][j];
                Case laCase = damier.getCase(i, j);

                if (laCase != null && laCase.estAllumee()) {
                    btn.setBackground(java.awt.Color.RED);
                } else {
                    btn.setBackground(java.awt.Color.DARK_GRAY);
                }

                if (cavalier.getX() == i && cavalier.getY() == j) {
                    btn.setText("C");
                    btn.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 40));
                    btn.setForeground(java.awt.Color.WHITE);
                } else {
                    btn.setText("");
                }
            }
        }

        if (jeu.getDamier().estNiveauTermine()) {
            labelEtat.setText("NIVEAU TERMINÉ ! BRAVO !");
            labelEtat.setForeground(java.awt.Color.GREEN);
        } else if (jeu.estBloque()) {
            labelEtat.setText("PARTIE PERDUE : VOUS ÊTES COINCÉ !");
            labelEtat.setForeground(java.awt.Color.RED);
        } else {
            labelEtat.setText("Partie en cours...");
            labelEtat.setForeground(java.awt.Color.BLACK);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 400, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface_graphique_chevauchee_fantastique().setVisible(true));
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
